# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Turtle Monitoring
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.analysis import (
    dataframe_column_sum as dataframe_column_sum,
)
from ecoscope_workflows_core.tasks.analysis import dataframe_count as dataframe_count
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import filter_df as filter_df
from ecoscope_workflows_ext_curacao.tasks import (
    apply_qualitative_color_map as apply_qualitative_color_map,
)
from ecoscope_workflows_ext_curacao.tasks import (
    compute_hatching_success_pct as compute_hatching_success_pct,
)
from ecoscope_workflows_ext_curacao.tasks import (
    create_fp_by_location_table as create_fp_by_location_table,
)
from ecoscope_workflows_ext_curacao.tasks import (
    create_nesting_by_beach_table as create_nesting_by_beach_table,
)
from ecoscope_workflows_ext_curacao.tasks import (
    create_nesting_success_by_manipulation_table as create_nesting_success_by_manipulation_table,
)
from ecoscope_workflows_ext_curacao.tasks import (
    create_nesting_success_by_species_beach_table as create_nesting_success_by_species_beach_table,
)
from ecoscope_workflows_ext_curacao.tasks import (
    create_turtle_events_by_location_table as create_turtle_events_by_location_table,
)
from ecoscope_workflows_ext_curacao.tasks import (
    extract_hatching_fields as extract_hatching_fields,
)
from ecoscope_workflows_ext_curacao.tasks import (
    extract_nesting_fields as extract_nesting_fields,
)
from ecoscope_workflows_ext_curacao.tasks import (
    extract_turtle_fields as extract_turtle_fields,
)
from ecoscope_workflows_ext_curacao.tasks import (
    gather_curacao_dashboard as gather_curacao_dashboard,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    process_events_details as process_events_details,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import get_events as get_events
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_table as draw_table
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_time_series_bar_chart as draw_time_series_bar_chart,
)

# %% [markdown]
# ## Workflow Details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Data Source

# %%
# parameters

er_client_params = dict(
    data_source=...,
)

# %%
# call the task


er_client = (
    set_er_connection.set_task_instance_id("er_client")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**er_client_params)
    .call()
)


# %% [markdown]
# ## Time Range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_format="%d %b %Y", **time_range_params)
    .call()
)


# %% [markdown]
# ## Base Maps

# %%
# parameters

base_maps_params = dict(
    base_maps=...,
)

# %%
# call the task


base_maps = (
    set_base_maps_pydeck.set_task_instance_id("base_maps")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**base_maps_params)
    .call()
)


# %% [markdown]
# ## Fetch All Events

# %%
# parameters

all_events_params = dict()

# %%
# call the task


all_events = (
    get_events.set_task_instance_id("all_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=er_client,
        time_range=time_range,
        event_columns=["id", "time", "event_type", "geometry", "event_details"],
        event_types=[
            "suspected_nest_v2",
            "attempt_v2",
            "dry_run_v2",
            "hatching_data",
            "relocation_data_v2",
            "turtle_data_form_v2",
        ],
        include_details=True,
        include_display_values=True,
        raise_on_empty=False,
        include_updates=False,
        include_related_events=False,
        include_null_geometry=False,
        **all_events_params,
    )
    .call()
)


# %% [markdown]
# ## Process Event Details

# %%
# parameters

all_events_processed_params = dict()

# %%
# call the task


all_events_processed = (
    process_events_details.set_task_instance_id("all_events_processed")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=all_events,
        client=er_client,
        map_to_titles=False,
        ordered=False,
        **all_events_processed_params,
    )
    .call()
)


# %% [markdown]
# ## Filter Nesting Events

# %%
# parameters

nesting_events_raw_params = dict()

# %%
# call the task


nesting_events_raw = (
    filter_row_values.set_task_instance_id("nesting_events_raw")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=all_events_processed,
        column="event_type",
        values=["suspected_nest_v2", "attempt_v2", "dry_run_v2"],
        **nesting_events_raw_params,
    )
    .call()
)


# %% [markdown]
# ## Filter Map Nesting Events

# %%
# parameters

map_nesting_events_raw_params = dict()

# %%
# call the task


map_nesting_events_raw = (
    filter_row_values.set_task_instance_id("map_nesting_events_raw")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=all_events_processed,
        column="event_type",
        values=["suspected_nest_v2", "attempt_v2", "relocation_data_v2"],
        **map_nesting_events_raw_params,
    )
    .call()
)


# %% [markdown]
# ## Filter Suspected Nest Events

# %%
# parameters

suspected_nest_events_params = dict()

# %%
# call the task


suspected_nest_events = (
    filter_row_values.set_task_instance_id("suspected_nest_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=all_events_processed,
        column="event_type",
        values=["suspected_nest_v2"],
        **suspected_nest_events_params,
    )
    .call()
)


# %% [markdown]
# ## Filter Hatching Events

# %%
# parameters

hatching_events_params = dict()

# %%
# call the task


hatching_events = (
    filter_row_values.set_task_instance_id("hatching_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=all_events_processed,
        column="event_type",
        values=["hatching_data"],
        **hatching_events_params,
    )
    .call()
)


# %% [markdown]
# ## Filter Turtle Events

# %%
# parameters

turtle_events_params = dict()

# %%
# call the task


turtle_events = (
    filter_row_values.set_task_instance_id("turtle_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=all_events_processed,
        column="event_type",
        values=["turtle_data_form_v2"],
        **turtle_events_params,
    )
    .call()
)


# %% [markdown]
# ## Extract Nesting Fields

# %%
# parameters

nesting_data_params = dict()

# %%
# call the task


nesting_data = (
    extract_nesting_fields.set_task_instance_id("nesting_data")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=nesting_events_raw, **nesting_data_params)
    .call()
)


# %% [markdown]
# ## Extract Map Nesting Fields

# %%
# parameters

map_nesting_data_params = dict()

# %%
# call the task


map_nesting_data = (
    extract_nesting_fields.set_task_instance_id("map_nesting_data")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=map_nesting_events_raw, **map_nesting_data_params)
    .call()
)


# %% [markdown]
# ## Extract Suspected Nest Fields

# %%
# parameters

suspected_nest_data_params = dict()

# %%
# call the task


suspected_nest_data = (
    extract_nesting_fields.set_task_instance_id("suspected_nest_data")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=suspected_nest_events, **suspected_nest_data_params)
    .call()
)


# %% [markdown]
# ## Extract Hatching Fields

# %%
# parameters

hatching_data_params = dict()

# %%
# call the task


hatching_data = (
    extract_hatching_fields.set_task_instance_id("hatching_data")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=hatching_events, **hatching_data_params)
    .call()
)


# %% [markdown]
# ## Extract Turtle Fields

# %%
# parameters

turtle_data_params = dict()

# %%
# call the task


turtle_data = (
    extract_turtle_fields.set_task_instance_id("turtle_data")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=turtle_events, **turtle_data_params)
    .call()
)


# %% [markdown]
# ## Total Nesting Events Count

# %%
# parameters

total_nesting_count_params = dict()

# %%
# call the task


total_nesting_count = (
    dataframe_count.set_task_instance_id("total_nesting_count")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=nesting_events_raw, **total_nesting_count_params)
    .call()
)


# %% [markdown]
# ## Total Nesting Events Widget

# %%
# parameters

total_nesting_widget_params = dict(
    view=...,
)

# %%
# call the task


total_nesting_widget = (
    create_single_value_widget_single_view.set_task_instance_id("total_nesting_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Total Nesting Events",
        decimal_places=0,
        data=total_nesting_count,
        **total_nesting_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Total Hatched Eggs

# %%
# parameters

total_hatched_eggs_params = dict()

# %%
# call the task


total_hatched_eggs = (
    dataframe_column_sum.set_task_instance_id("total_hatched_eggs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=hatching_data,
        column_name="hatchedempty_egg_shells",
        **total_hatched_eggs_params,
    )
    .call()
)


# %% [markdown]
# ## Total Hatched Eggs Widget

# %%
# parameters

total_hatched_eggs_widget_params = dict(
    view=...,
)

# %%
# call the task


total_hatched_eggs_widget = (
    create_single_value_widget_single_view.set_task_instance_id(
        "total_hatched_eggs_widget"
    )
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Total Hatched Eggs",
        decimal_places=0,
        data=total_hatched_eggs,
        **total_hatched_eggs_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Hatching Success Percentage

# %%
# parameters

hatching_success_pct_params = dict()

# %%
# call the task


hatching_success_pct = (
    compute_hatching_success_pct.set_task_instance_id("hatching_success_pct")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=hatching_data, **hatching_success_pct_params)
    .call()
)


# %% [markdown]
# ## Hatching Success Widget

# %%
# parameters

hatching_success_widget_params = dict(
    view=...,
)

# %%
# call the task


hatching_success_widget = (
    create_single_value_widget_single_view.set_task_instance_id(
        "hatching_success_widget"
    )
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Hatching Success (%)",
        decimal_places=1,
        data=hatching_success_pct,
        **hatching_success_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Total Turtle-Related Events Count

# %%
# parameters

total_turtle_count_params = dict()

# %%
# call the task


total_turtle_count = (
    dataframe_count.set_task_instance_id("total_turtle_count")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=turtle_events, **total_turtle_count_params)
    .call()
)


# %% [markdown]
# ## Total Turtle-Related Events Widget

# %%
# parameters

total_turtle_widget_params = dict(
    view=...,
)

# %%
# call the task


total_turtle_widget = (
    create_single_value_widget_single_view.set_task_instance_id("total_turtle_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Total Turtle-Related Events",
        decimal_places=0,
        data=total_turtle_count,
        **total_turtle_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Filter Turtles with FP

# %%
# parameters

fp_events_params = dict()

# %%
# call the task


fp_events = (
    filter_df.set_task_instance_id("fp_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=turtle_data,
        column_name="fibropapillomatosis",
        op="equal",
        value="yes",
        reset_index=True,
        **fp_events_params,
    )
    .call()
)


# %% [markdown]
# ## Total Turtles with FP Count

# %%
# parameters

total_fp_count_params = dict()

# %%
# call the task


total_fp_count = (
    dataframe_count.set_task_instance_id("total_fp_count")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=fp_events, **total_fp_count_params)
    .call()
)


# %% [markdown]
# ## Total Turtles with FP Widget

# %%
# parameters

total_fp_widget_params = dict(
    view=...,
)

# %%
# call the task


total_fp_widget = (
    create_single_value_widget_single_view.set_task_instance_id("total_fp_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Total Turtles with FP",
        decimal_places=0,
        data=total_fp_count,
        **total_fp_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Color Map - Nesting Activity

# %%
# parameters

nesting_colormap_params = dict()

# %%
# call the task


nesting_colormap = (
    apply_qualitative_color_map.set_task_instance_id("nesting_colormap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=map_nesting_data,
        input_column_name="event_type_display",
        colormap="Set1",
        custom_colors=None,
        **nesting_colormap_params,
    )
    .call()
)


# %% [markdown]
# ## Nesting Points Layer

# %%
# parameters

nesting_layer_params = dict()

# %%
# call the task


nesting_layer = (
    create_scatterplot_layer.set_task_instance_id("nesting_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        geodataframe=nesting_colormap,
        layer_style={
            "get_fill_color": "column_color",
            "get_radius": 5,
            "radius_units": "pixels",
        },
        legend={
            "title": "Nesting Activity",
            "label_column": "column_label",
            "color_column": "column_color",
        },
        data_url=None,
        **nesting_layer_params,
    )
    .call()
)


# %% [markdown]
# ## Nesting Activity Map

# %%
# parameters

nesting_map_params = dict(
    widget_id=...,
)

# %%
# call the task


nesting_map = (
    draw_map.set_task_instance_id("nesting_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        geo_layers=nesting_layer,
        tile_layers=base_maps,
        static=False,
        title=None,
        max_zoom=15,
        view_state=None,
        legend_style={"placement": "bottom-right"},
        **nesting_map_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

persist_nesting_map_params = dict(
    filename=...,
)

# %%
# call the task


persist_nesting_map = (
    persist_text.set_task_instance_id("persist_nesting_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        text=nesting_map,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="nesting_map",
        **persist_nesting_map_params,
    )
    .call()
)


# %% [markdown]
# ## Nesting Activity Map Widget

# %%
# parameters

nesting_map_widget_params = dict(
    view=...,
)

# %%
# call the task


nesting_map_widget = (
    create_map_widget_single_view.set_task_instance_id("nesting_map_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Nesting Activity Map",
        data=persist_nesting_map,
        **nesting_map_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Nesting Activity Over Time Chart

# %%
# parameters

nesting_over_time_chart_params = dict()

# %%
# call the task


nesting_over_time_chart = (
    draw_time_series_bar_chart.set_task_instance_id("nesting_over_time_chart")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        dataframe=nesting_data,
        x_axis="time",
        y_axis="count",
        category="specie",
        agg_function="sum",
        time_interval="month",
        color_column=None,
        layout_style={
            "barmode": "group",
            "xaxis": {"title": "Month"},
            "yaxis": {"title": "Nesting Events"},
        },
        plot_style=None,
        widget_id="nesting_over_time_widget",
        **nesting_over_time_chart_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

persist_nesting_over_time_params = dict(
    filename=...,
)

# %%
# call the task


persist_nesting_over_time = (
    persist_text.set_task_instance_id("persist_nesting_over_time")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        text=nesting_over_time_chart,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="nesting_over_time",
        **persist_nesting_over_time_params,
    )
    .call()
)


# %% [markdown]
# ## Nesting Activity Over Time Widget

# %%
# parameters

nesting_over_time_widget_params = dict(
    view=...,
)

# %%
# call the task


nesting_over_time_widget = (
    create_plot_widget_single_view.set_task_instance_id("nesting_over_time_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Nesting Activity Over Time",
        data=persist_nesting_over_time,
        **nesting_over_time_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Nesting by Beach Table

# %%
# parameters

nesting_by_beach_df_params = dict()

# %%
# call the task


nesting_by_beach_df = (
    create_nesting_by_beach_table.set_task_instance_id("nesting_by_beach_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=nesting_data, **nesting_by_beach_df_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

nesting_by_beach_drawn_params = dict()

# %%
# call the task


nesting_by_beach_drawn = (
    draw_table.set_task_instance_id("nesting_by_beach_drawn")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        dataframe=nesting_by_beach_df,
        columns=None,
        table_config=None,
        widget_id="nesting_by_beach_widget",
        **nesting_by_beach_drawn_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

persist_nesting_by_beach_params = dict(
    filename=...,
)

# %%
# call the task


persist_nesting_by_beach = (
    persist_text.set_task_instance_id("persist_nesting_by_beach")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        text=nesting_by_beach_drawn,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="nesting_by_beach",
        **persist_nesting_by_beach_params,
    )
    .call()
)


# %% [markdown]
# ## Nesting by Beach Widget

# %%
# parameters

nesting_by_beach_widget_params = dict(
    view=...,
)

# %%
# call the task


nesting_by_beach_widget = (
    create_plot_widget_single_view.set_task_instance_id("nesting_by_beach_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Total Nesting Activity by Beach",
        data=persist_nesting_by_beach,
        **nesting_by_beach_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Nesting Success by Species & Beach Table

# %%
# parameters

nesting_success_species_beach_df_params = dict()

# %%
# call the task


nesting_success_species_beach_df = (
    create_nesting_success_by_species_beach_table.set_task_instance_id(
        "nesting_success_species_beach_df"
    )
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=hatching_data, **nesting_success_species_beach_df_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

nest_success_sp_beach_drawn_params = dict()

# %%
# call the task


nest_success_sp_beach_drawn = (
    draw_table.set_task_instance_id("nest_success_sp_beach_drawn")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        dataframe=nesting_success_species_beach_df,
        columns=None,
        table_config=None,
        widget_id="nest_success_sp_beach_widget",
        **nest_success_sp_beach_drawn_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

persist_nest_success_sp_beach_params = dict(
    filename=...,
)

# %%
# call the task


persist_nest_success_sp_beach = (
    persist_text.set_task_instance_id("persist_nest_success_sp_beach")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        text=nest_success_sp_beach_drawn,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="nesting_success_species_beach",
        **persist_nest_success_sp_beach_params,
    )
    .call()
)


# %% [markdown]
# ## Nesting Success by Species & Beach Widget

# %%
# parameters

nest_success_sp_beach_widget_params = dict(
    view=...,
)

# %%
# call the task


nest_success_sp_beach_widget = (
    create_plot_widget_single_view.set_task_instance_id("nest_success_sp_beach_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Nesting Success by Species & Beach",
        data=persist_nest_success_sp_beach,
        **nest_success_sp_beach_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Nesting Success by Manipulation Table

# %%
# parameters

nesting_success_manipulation_df_params = dict()

# %%
# call the task


nesting_success_manipulation_df = (
    create_nesting_success_by_manipulation_table.set_task_instance_id(
        "nesting_success_manipulation_df"
    )
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=hatching_data, **nesting_success_manipulation_df_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

nest_success_manip_drawn_params = dict()

# %%
# call the task


nest_success_manip_drawn = (
    draw_table.set_task_instance_id("nest_success_manip_drawn")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        dataframe=nesting_success_manipulation_df,
        columns=None,
        table_config=None,
        widget_id="nest_success_manip_widget",
        **nest_success_manip_drawn_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

persist_nest_success_manip_params = dict(
    filename=...,
)

# %%
# call the task


persist_nest_success_manip = (
    persist_text.set_task_instance_id("persist_nest_success_manip")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        text=nest_success_manip_drawn,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="nesting_success_manipulation",
        **persist_nest_success_manip_params,
    )
    .call()
)


# %% [markdown]
# ## Nesting Success by Manipulation Widget

# %%
# parameters

nest_success_manip_widget_params = dict(
    view=...,
)

# %%
# call the task


nest_success_manip_widget = (
    create_plot_widget_single_view.set_task_instance_id("nest_success_manip_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Nesting Success by Nest Manipulation",
        data=persist_nest_success_manip,
        **nest_success_manip_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Color Map - Turtle Activity

# %%
# parameters

turtle_colormap_params = dict()

# %%
# call the task


turtle_colormap = (
    apply_qualitative_color_map.set_task_instance_id("turtle_colormap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=turtle_data,
        input_column_name="activity_type",
        colormap="Set2",
        custom_colors=None,
        **turtle_colormap_params,
    )
    .call()
)


# %% [markdown]
# ## Turtle Events Layer

# %%
# parameters

turtle_layer_params = dict()

# %%
# call the task


turtle_layer = (
    create_scatterplot_layer.set_task_instance_id("turtle_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        geodataframe=turtle_colormap,
        layer_style={
            "get_fill_color": "column_color",
            "get_radius": 5,
            "radius_units": "pixels",
        },
        legend={
            "title": "Turtle Events",
            "label_column": "column_label",
            "color_column": "column_color",
        },
        data_url=None,
        **turtle_layer_params,
    )
    .call()
)


# %% [markdown]
# ## Turtle Events Map

# %%
# parameters

turtle_map_params = dict(
    widget_id=...,
)

# %%
# call the task


turtle_map = (
    draw_map.set_task_instance_id("turtle_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        geo_layers=turtle_layer,
        tile_layers=base_maps,
        static=False,
        title=None,
        max_zoom=15,
        view_state=None,
        legend_style={"placement": "bottom-right"},
        **turtle_map_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

persist_turtle_map_params = dict(
    filename=...,
)

# %%
# call the task


persist_turtle_map = (
    persist_text.set_task_instance_id("persist_turtle_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        text=turtle_map,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="turtle_map",
        **persist_turtle_map_params,
    )
    .call()
)


# %% [markdown]
# ## Turtle Events Map Widget

# %%
# parameters

turtle_map_widget_params = dict(
    view=...,
)

# %%
# call the task


turtle_map_widget = (
    create_map_widget_single_view.set_task_instance_id("turtle_map_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Turtle-Related Events Map",
        data=persist_turtle_map,
        **turtle_map_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Turtle Events by Location Table

# %%
# parameters

turtle_events_by_location_df_params = dict()

# %%
# call the task


turtle_events_by_location_df = (
    create_turtle_events_by_location_table.set_task_instance_id(
        "turtle_events_by_location_df"
    )
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=turtle_data, **turtle_events_by_location_df_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

turtle_events_by_location_drawn_params = dict()

# %%
# call the task


turtle_events_by_location_drawn = (
    draw_table.set_task_instance_id("turtle_events_by_location_drawn")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        dataframe=turtle_events_by_location_df,
        columns=None,
        table_config=None,
        widget_id="turtle_events_by_location_widget",
        **turtle_events_by_location_drawn_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

persist_turtle_events_by_loc_params = dict(
    filename=...,
)

# %%
# call the task


persist_turtle_events_by_loc = (
    persist_text.set_task_instance_id("persist_turtle_events_by_loc")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        text=turtle_events_by_location_drawn,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="turtle_events_by_location",
        **persist_turtle_events_by_loc_params,
    )
    .call()
)


# %% [markdown]
# ## Turtle Events by Location Widget

# %%
# parameters

turtle_events_by_location_widget_params = dict(
    view=...,
)

# %%
# call the task


turtle_events_by_location_widget = (
    create_plot_widget_single_view.set_task_instance_id(
        "turtle_events_by_location_widget"
    )
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Turtle Events by Location & Activity",
        data=persist_turtle_events_by_loc,
        **turtle_events_by_location_widget_params,
    )
    .call()
)


# %% [markdown]
# ## FP by Location Table

# %%
# parameters

fp_by_location_df_params = dict()

# %%
# call the task


fp_by_location_df = (
    create_fp_by_location_table.set_task_instance_id("fp_by_location_df")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=turtle_data, **fp_by_location_df_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

fp_by_location_drawn_params = dict()

# %%
# call the task


fp_by_location_drawn = (
    draw_table.set_task_instance_id("fp_by_location_drawn")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        dataframe=fp_by_location_df,
        columns=None,
        table_config=None,
        widget_id="fp_by_location_widget",
        **fp_by_location_drawn_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

persist_fp_by_location_params = dict(
    filename=...,
)

# %%
# call the task


persist_fp_by_location = (
    persist_text.set_task_instance_id("persist_fp_by_location")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        text=fp_by_location_drawn,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="fp_by_location",
        **persist_fp_by_location_params,
    )
    .call()
)


# %% [markdown]
# ## FP by Location Widget

# %%
# parameters

fp_by_location_widget_params = dict(
    view=...,
)

# %%
# call the task


fp_by_location_widget = (
    create_plot_widget_single_view.set_task_instance_id("fp_by_location_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="FP Monitoring by Location",
        data=persist_fp_by_location,
        **fp_by_location_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Create Dashboard

# %%
# parameters

dashboard_params = dict(
    groupers=...,
)

# %%
# call the task


dashboard = (
    gather_curacao_dashboard.set_task_instance_id("dashboard")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        details=workflow_details,
        widgets=[
            total_nesting_widget,
            total_hatched_eggs_widget,
            hatching_success_widget,
            total_turtle_widget,
            total_fp_widget,
            nesting_map_widget,
            nesting_over_time_widget,
            nesting_by_beach_widget,
            nest_success_sp_beach_widget,
            nest_success_manip_widget,
            turtle_map_widget,
            turtle_events_by_location_widget,
            fp_by_location_widget,
        ],
        time_range=time_range,
        **dashboard_params,
    )
    .call()
)
