# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.tasks.analysis import (
    dataframe_column_sum as dataframe_column_sum,
)
from ecoscope_workflows_core.tasks.analysis import dataframe_count as dataframe_count
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import filter_df as filter_df
from ecoscope_workflows_ext_curacao.tasks import (
    apply_qualitative_color_map as apply_qualitative_color_map,
)
from ecoscope_workflows_ext_curacao.tasks import (
    compute_hatching_success_pct as compute_hatching_success_pct,
)
from ecoscope_workflows_ext_curacao.tasks import (
    create_fp_by_location_table as create_fp_by_location_table,
)
from ecoscope_workflows_ext_curacao.tasks import (
    create_nesting_by_beach_table as create_nesting_by_beach_table,
)
from ecoscope_workflows_ext_curacao.tasks import (
    create_nesting_success_by_manipulation_table as create_nesting_success_by_manipulation_table,
)
from ecoscope_workflows_ext_curacao.tasks import (
    create_nesting_success_by_species_beach_table as create_nesting_success_by_species_beach_table,
)
from ecoscope_workflows_ext_curacao.tasks import (
    create_turtle_events_by_location_table as create_turtle_events_by_location_table,
)
from ecoscope_workflows_ext_curacao.tasks import (
    extract_hatching_fields as extract_hatching_fields,
)
from ecoscope_workflows_ext_curacao.tasks import (
    extract_nesting_fields as extract_nesting_fields,
)
from ecoscope_workflows_ext_curacao.tasks import (
    extract_turtle_fields as extract_turtle_fields,
)
from ecoscope_workflows_ext_curacao.tasks import (
    gather_curacao_dashboard as gather_curacao_dashboard,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    process_events_details as process_events_details,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import get_events as get_events
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_table as draw_table
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_time_series_bar_chart as draw_time_series_bar_chart,
)

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    er_client = (
        set_er_connection.validate()
        .set_task_instance_id("er_client")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("er_client") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y", **(params_dict.get("time_range") or {}))
        .call()
    )

    base_maps = (
        set_base_maps_pydeck.validate()
        .set_task_instance_id("base_maps")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("base_maps") or {}))
        .call()
    )

    all_events = (
        get_events.validate()
        .set_task_instance_id("all_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            time_range=time_range,
            event_columns=["id", "time", "event_type", "geometry", "event_details"],
            event_types=[
                "suspected_nest_v2",
                "attempt_v2",
                "dry_run_v2",
                "hatching_data",
                "relocation_data_v2",
                "turtle_data_form_v2",
            ],
            include_details=True,
            include_display_values=True,
            raise_on_empty=False,
            include_updates=False,
            include_related_events=False,
            include_null_geometry=False,
            **(params_dict.get("all_events") or {}),
        )
        .call()
    )

    all_events_processed = (
        process_events_details.validate()
        .set_task_instance_id("all_events_processed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=all_events,
            client=er_client,
            map_to_titles=False,
            ordered=False,
            **(params_dict.get("all_events_processed") or {}),
        )
        .call()
    )

    nesting_events_raw = (
        filter_row_values.validate()
        .set_task_instance_id("nesting_events_raw")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=all_events_processed,
            column="event_type",
            values=["suspected_nest_v2", "attempt_v2", "dry_run_v2"],
            **(params_dict.get("nesting_events_raw") or {}),
        )
        .call()
    )

    map_nesting_events_raw = (
        filter_row_values.validate()
        .set_task_instance_id("map_nesting_events_raw")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=all_events_processed,
            column="event_type",
            values=["suspected_nest_v2", "attempt_v2", "relocation_data_v2"],
            **(params_dict.get("map_nesting_events_raw") or {}),
        )
        .call()
    )

    suspected_nest_events = (
        filter_row_values.validate()
        .set_task_instance_id("suspected_nest_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=all_events_processed,
            column="event_type",
            values=["suspected_nest_v2"],
            **(params_dict.get("suspected_nest_events") or {}),
        )
        .call()
    )

    hatching_events = (
        filter_row_values.validate()
        .set_task_instance_id("hatching_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=all_events_processed,
            column="event_type",
            values=["hatching_data"],
            **(params_dict.get("hatching_events") or {}),
        )
        .call()
    )

    turtle_events = (
        filter_row_values.validate()
        .set_task_instance_id("turtle_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=all_events_processed,
            column="event_type",
            values=["turtle_data_form_v2"],
            **(params_dict.get("turtle_events") or {}),
        )
        .call()
    )

    nesting_data = (
        extract_nesting_fields.validate()
        .set_task_instance_id("nesting_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=nesting_events_raw, **(params_dict.get("nesting_data") or {}))
        .call()
    )

    map_nesting_data = (
        extract_nesting_fields.validate()
        .set_task_instance_id("map_nesting_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_nesting_events_raw, **(params_dict.get("map_nesting_data") or {})
        )
        .call()
    )

    suspected_nest_data = (
        extract_nesting_fields.validate()
        .set_task_instance_id("suspected_nest_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=suspected_nest_events, **(params_dict.get("suspected_nest_data") or {})
        )
        .call()
    )

    hatching_data = (
        extract_hatching_fields.validate()
        .set_task_instance_id("hatching_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=hatching_events, **(params_dict.get("hatching_data") or {}))
        .call()
    )

    turtle_data = (
        extract_turtle_fields.validate()
        .set_task_instance_id("turtle_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=turtle_events, **(params_dict.get("turtle_data") or {}))
        .call()
    )

    total_nesting_count = (
        dataframe_count.validate()
        .set_task_instance_id("total_nesting_count")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=nesting_events_raw, **(params_dict.get("total_nesting_count") or {})
        )
        .call()
    )

    total_nesting_widget = (
        create_single_value_widget_single_view.validate()
        .set_task_instance_id("total_nesting_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total Nesting Events",
            decimal_places=0,
            data=total_nesting_count,
            **(params_dict.get("total_nesting_widget") or {}),
        )
        .call()
    )

    total_hatched_eggs = (
        dataframe_column_sum.validate()
        .set_task_instance_id("total_hatched_eggs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=hatching_data,
            column_name="hatchedempty_egg_shells",
            **(params_dict.get("total_hatched_eggs") or {}),
        )
        .call()
    )

    total_hatched_eggs_widget = (
        create_single_value_widget_single_view.validate()
        .set_task_instance_id("total_hatched_eggs_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total Hatched Eggs",
            decimal_places=0,
            data=total_hatched_eggs,
            **(params_dict.get("total_hatched_eggs_widget") or {}),
        )
        .call()
    )

    hatching_success_pct = (
        compute_hatching_success_pct.validate()
        .set_task_instance_id("hatching_success_pct")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=hatching_data, **(params_dict.get("hatching_success_pct") or {}))
        .call()
    )

    hatching_success_widget = (
        create_single_value_widget_single_view.validate()
        .set_task_instance_id("hatching_success_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Hatching Success (%)",
            decimal_places=1,
            data=hatching_success_pct,
            **(params_dict.get("hatching_success_widget") or {}),
        )
        .call()
    )

    total_turtle_count = (
        dataframe_count.validate()
        .set_task_instance_id("total_turtle_count")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=turtle_events, **(params_dict.get("total_turtle_count") or {}))
        .call()
    )

    total_turtle_widget = (
        create_single_value_widget_single_view.validate()
        .set_task_instance_id("total_turtle_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total Turtle-Related Events",
            decimal_places=0,
            data=total_turtle_count,
            **(params_dict.get("total_turtle_widget") or {}),
        )
        .call()
    )

    fp_events = (
        filter_df.validate()
        .set_task_instance_id("fp_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=turtle_data,
            column_name="fibropapillomatosis",
            op="equal",
            value="yes",
            reset_index=True,
            **(params_dict.get("fp_events") or {}),
        )
        .call()
    )

    total_fp_count = (
        dataframe_count.validate()
        .set_task_instance_id("total_fp_count")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=fp_events, **(params_dict.get("total_fp_count") or {}))
        .call()
    )

    total_fp_widget = (
        create_single_value_widget_single_view.validate()
        .set_task_instance_id("total_fp_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total Turtles with FP",
            decimal_places=0,
            data=total_fp_count,
            **(params_dict.get("total_fp_widget") or {}),
        )
        .call()
    )

    nesting_colormap = (
        apply_qualitative_color_map.validate()
        .set_task_instance_id("nesting_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_nesting_data,
            input_column_name="event_type_display",
            colormap="Set1",
            custom_colors=None,
            **(params_dict.get("nesting_colormap") or {}),
        )
        .call()
    )

    nesting_layer = (
        create_scatterplot_layer.validate()
        .set_task_instance_id("nesting_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=nesting_colormap,
            layer_style={
                "get_fill_color": "column_color",
                "get_radius": 5,
                "radius_units": "pixels",
            },
            legend={
                "title": "Nesting Activity",
                "label_column": "column_label",
                "color_column": "column_color",
            },
            data_url=None,
            **(params_dict.get("nesting_layer") or {}),
        )
        .call()
    )

    nesting_map = (
        draw_map.validate()
        .set_task_instance_id("nesting_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geo_layers=nesting_layer,
            tile_layers=base_maps,
            static=False,
            title=None,
            max_zoom=15,
            view_state=None,
            legend_style={"placement": "bottom-right"},
            **(params_dict.get("nesting_map") or {}),
        )
        .call()
    )

    persist_nesting_map = (
        persist_text.validate()
        .set_task_instance_id("persist_nesting_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=nesting_map,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="nesting_map",
            **(params_dict.get("persist_nesting_map") or {}),
        )
        .call()
    )

    nesting_map_widget = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("nesting_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Nesting Activity Map",
            data=persist_nesting_map,
            **(params_dict.get("nesting_map_widget") or {}),
        )
        .call()
    )

    nesting_over_time_chart = (
        draw_time_series_bar_chart.validate()
        .set_task_instance_id("nesting_over_time_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=nesting_data,
            x_axis="time",
            y_axis="count",
            category="specie",
            agg_function="sum",
            time_interval="month",
            color_column=None,
            layout_style={
                "barmode": "group",
                "xaxis": {"title": "Month"},
                "yaxis": {"title": "Nesting Events"},
            },
            plot_style=None,
            widget_id="nesting_over_time_widget",
            **(params_dict.get("nesting_over_time_chart") or {}),
        )
        .call()
    )

    persist_nesting_over_time = (
        persist_text.validate()
        .set_task_instance_id("persist_nesting_over_time")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=nesting_over_time_chart,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="nesting_over_time",
            **(params_dict.get("persist_nesting_over_time") or {}),
        )
        .call()
    )

    nesting_over_time_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("nesting_over_time_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Nesting Activity Over Time",
            data=persist_nesting_over_time,
            **(params_dict.get("nesting_over_time_widget") or {}),
        )
        .call()
    )

    nesting_by_beach_df = (
        create_nesting_by_beach_table.validate()
        .set_task_instance_id("nesting_by_beach_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=nesting_data, **(params_dict.get("nesting_by_beach_df") or {}))
        .call()
    )

    nesting_by_beach_drawn = (
        draw_table.validate()
        .set_task_instance_id("nesting_by_beach_drawn")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=nesting_by_beach_df,
            columns=None,
            table_config=None,
            widget_id="nesting_by_beach_widget",
            **(params_dict.get("nesting_by_beach_drawn") or {}),
        )
        .call()
    )

    persist_nesting_by_beach = (
        persist_text.validate()
        .set_task_instance_id("persist_nesting_by_beach")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=nesting_by_beach_drawn,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="nesting_by_beach",
            **(params_dict.get("persist_nesting_by_beach") or {}),
        )
        .call()
    )

    nesting_by_beach_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("nesting_by_beach_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total Nesting Activity by Beach",
            data=persist_nesting_by_beach,
            **(params_dict.get("nesting_by_beach_widget") or {}),
        )
        .call()
    )

    nesting_success_species_beach_df = (
        create_nesting_success_by_species_beach_table.validate()
        .set_task_instance_id("nesting_success_species_beach_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=hatching_data,
            **(params_dict.get("nesting_success_species_beach_df") or {}),
        )
        .call()
    )

    nest_success_sp_beach_drawn = (
        draw_table.validate()
        .set_task_instance_id("nest_success_sp_beach_drawn")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=nesting_success_species_beach_df,
            columns=None,
            table_config=None,
            widget_id="nest_success_sp_beach_widget",
            **(params_dict.get("nest_success_sp_beach_drawn") or {}),
        )
        .call()
    )

    persist_nest_success_sp_beach = (
        persist_text.validate()
        .set_task_instance_id("persist_nest_success_sp_beach")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=nest_success_sp_beach_drawn,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="nesting_success_species_beach",
            **(params_dict.get("persist_nest_success_sp_beach") or {}),
        )
        .call()
    )

    nest_success_sp_beach_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("nest_success_sp_beach_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Nesting Success by Species & Beach",
            data=persist_nest_success_sp_beach,
            **(params_dict.get("nest_success_sp_beach_widget") or {}),
        )
        .call()
    )

    nesting_success_manipulation_df = (
        create_nesting_success_by_manipulation_table.validate()
        .set_task_instance_id("nesting_success_manipulation_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=hatching_data,
            **(params_dict.get("nesting_success_manipulation_df") or {}),
        )
        .call()
    )

    nest_success_manip_drawn = (
        draw_table.validate()
        .set_task_instance_id("nest_success_manip_drawn")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=nesting_success_manipulation_df,
            columns=None,
            table_config=None,
            widget_id="nest_success_manip_widget",
            **(params_dict.get("nest_success_manip_drawn") or {}),
        )
        .call()
    )

    persist_nest_success_manip = (
        persist_text.validate()
        .set_task_instance_id("persist_nest_success_manip")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=nest_success_manip_drawn,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="nesting_success_manipulation",
            **(params_dict.get("persist_nest_success_manip") or {}),
        )
        .call()
    )

    nest_success_manip_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("nest_success_manip_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Nesting Success by Nest Manipulation",
            data=persist_nest_success_manip,
            **(params_dict.get("nest_success_manip_widget") or {}),
        )
        .call()
    )

    turtle_colormap = (
        apply_qualitative_color_map.validate()
        .set_task_instance_id("turtle_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=turtle_data,
            input_column_name="activity_type",
            colormap="Set2",
            custom_colors=None,
            **(params_dict.get("turtle_colormap") or {}),
        )
        .call()
    )

    turtle_layer = (
        create_scatterplot_layer.validate()
        .set_task_instance_id("turtle_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=turtle_colormap,
            layer_style={
                "get_fill_color": "column_color",
                "get_radius": 5,
                "radius_units": "pixels",
            },
            legend={
                "title": "Turtle Events",
                "label_column": "column_label",
                "color_column": "column_color",
            },
            data_url=None,
            **(params_dict.get("turtle_layer") or {}),
        )
        .call()
    )

    turtle_map = (
        draw_map.validate()
        .set_task_instance_id("turtle_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geo_layers=turtle_layer,
            tile_layers=base_maps,
            static=False,
            title=None,
            max_zoom=15,
            view_state=None,
            legend_style={"placement": "bottom-right"},
            **(params_dict.get("turtle_map") or {}),
        )
        .call()
    )

    persist_turtle_map = (
        persist_text.validate()
        .set_task_instance_id("persist_turtle_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=turtle_map,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="turtle_map",
            **(params_dict.get("persist_turtle_map") or {}),
        )
        .call()
    )

    turtle_map_widget = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("turtle_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Turtle-Related Events Map",
            data=persist_turtle_map,
            **(params_dict.get("turtle_map_widget") or {}),
        )
        .call()
    )

    turtle_events_by_location_df = (
        create_turtle_events_by_location_table.validate()
        .set_task_instance_id("turtle_events_by_location_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=turtle_data, **(params_dict.get("turtle_events_by_location_df") or {})
        )
        .call()
    )

    turtle_events_by_location_drawn = (
        draw_table.validate()
        .set_task_instance_id("turtle_events_by_location_drawn")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=turtle_events_by_location_df,
            columns=None,
            table_config=None,
            widget_id="turtle_events_by_location_widget",
            **(params_dict.get("turtle_events_by_location_drawn") or {}),
        )
        .call()
    )

    persist_turtle_events_by_loc = (
        persist_text.validate()
        .set_task_instance_id("persist_turtle_events_by_loc")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=turtle_events_by_location_drawn,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="turtle_events_by_location",
            **(params_dict.get("persist_turtle_events_by_loc") or {}),
        )
        .call()
    )

    turtle_events_by_location_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("turtle_events_by_location_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Turtle Events by Location & Activity",
            data=persist_turtle_events_by_loc,
            **(params_dict.get("turtle_events_by_location_widget") or {}),
        )
        .call()
    )

    fp_by_location_df = (
        create_fp_by_location_table.validate()
        .set_task_instance_id("fp_by_location_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=turtle_data, **(params_dict.get("fp_by_location_df") or {}))
        .call()
    )

    fp_by_location_drawn = (
        draw_table.validate()
        .set_task_instance_id("fp_by_location_drawn")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=fp_by_location_df,
            columns=None,
            table_config=None,
            widget_id="fp_by_location_widget",
            **(params_dict.get("fp_by_location_drawn") or {}),
        )
        .call()
    )

    persist_fp_by_location = (
        persist_text.validate()
        .set_task_instance_id("persist_fp_by_location")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=fp_by_location_drawn,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="fp_by_location",
            **(params_dict.get("persist_fp_by_location") or {}),
        )
        .call()
    )

    fp_by_location_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("fp_by_location_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="FP Monitoring by Location",
            data=persist_fp_by_location,
            **(params_dict.get("fp_by_location_widget") or {}),
        )
        .call()
    )

    dashboard = (
        gather_curacao_dashboard.validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                total_nesting_widget,
                total_hatched_eggs_widget,
                hatching_success_widget,
                total_turtle_widget,
                total_fp_widget,
                nesting_map_widget,
                nesting_over_time_widget,
                nesting_by_beach_widget,
                nest_success_sp_beach_widget,
                nest_success_manip_widget,
                turtle_map_widget,
                turtle_events_by_location_widget,
                fp_by_location_widget,
            ],
            time_range=time_range,
            **(params_dict.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
