# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)

get_events = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_events",  # 🧪
)  # 🧪

process_events_details = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.analysis import (
    dataframe_column_sum as dataframe_column_sum,
)
from ecoscope_workflows_core.tasks.analysis import dataframe_count as dataframe_count
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import filter_df as filter_df
from ecoscope_workflows_ext_curacao.tasks import (
    aggregate_nesting_by_month_species as aggregate_nesting_by_month_species,
)
from ecoscope_workflows_ext_curacao.tasks import (
    apply_qualitative_color_map as apply_qualitative_color_map,
)
from ecoscope_workflows_ext_curacao.tasks import (
    compute_hatching_success_pct as compute_hatching_success_pct,
)
from ecoscope_workflows_ext_curacao.tasks import (
    create_fp_by_location_table as create_fp_by_location_table,
)
from ecoscope_workflows_ext_curacao.tasks import (
    create_nesting_by_beach_table as create_nesting_by_beach_table,
)
from ecoscope_workflows_ext_curacao.tasks import (
    create_nesting_success_by_manipulation_table as create_nesting_success_by_manipulation_table,
)
from ecoscope_workflows_ext_curacao.tasks import (
    create_nesting_success_by_species_beach_table as create_nesting_success_by_species_beach_table,
)
from ecoscope_workflows_ext_curacao.tasks import (
    create_turtle_events_by_location_table as create_turtle_events_by_location_table,
)
from ecoscope_workflows_ext_curacao.tasks import (
    extract_hatching_fields as extract_hatching_fields,
)
from ecoscope_workflows_ext_curacao.tasks import (
    extract_nesting_fields as extract_nesting_fields,
)
from ecoscope_workflows_ext_curacao.tasks import (
    extract_turtle_fields as extract_turtle_fields,
)
from ecoscope_workflows_ext_curacao.tasks import (
    gather_curacao_dashboard as gather_curacao_dashboard,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_line_chart as draw_line_chart,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_table as draw_table

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "er_client": [],
        "time_range": [],
        "base_maps": [],
        "all_events": ["er_client", "time_range"],
        "all_events_processed": ["all_events", "er_client"],
        "nesting_events_raw": ["all_events_processed"],
        "map_nesting_events_raw": ["all_events_processed"],
        "suspected_nest_events": ["all_events_processed"],
        "hatching_events": ["all_events_processed"],
        "turtle_events": ["all_events_processed"],
        "nesting_data": ["nesting_events_raw"],
        "map_nesting_data": ["map_nesting_events_raw"],
        "suspected_nest_data": ["suspected_nest_events"],
        "hatching_data": ["hatching_events"],
        "turtle_data": ["turtle_events"],
        "total_nesting_count": ["nesting_events_raw"],
        "total_nesting_widget": ["total_nesting_count"],
        "total_hatched_eggs": ["hatching_data"],
        "total_hatched_eggs_widget": ["total_hatched_eggs"],
        "hatching_success_pct": ["hatching_data"],
        "hatching_success_widget": ["hatching_success_pct"],
        "total_turtle_count": ["turtle_events"],
        "total_turtle_widget": ["total_turtle_count"],
        "fp_events": ["turtle_data"],
        "total_fp_count": ["fp_events"],
        "total_fp_widget": ["total_fp_count"],
        "nesting_colormap": ["map_nesting_data"],
        "nesting_layer": ["nesting_colormap"],
        "nesting_map": ["nesting_layer", "base_maps"],
        "persist_nesting_map": ["nesting_map"],
        "nesting_map_widget": ["persist_nesting_map"],
        "nesting_over_time_agg": ["nesting_data"],
        "nesting_over_time_chart": ["nesting_over_time_agg"],
        "persist_nesting_over_time": ["nesting_over_time_chart"],
        "nesting_over_time_widget": ["persist_nesting_over_time"],
        "nesting_by_beach_df": ["nesting_data"],
        "nesting_by_beach_drawn": ["nesting_by_beach_df"],
        "persist_nesting_by_beach": ["nesting_by_beach_drawn"],
        "nesting_by_beach_widget": ["persist_nesting_by_beach"],
        "nesting_success_species_beach_df": ["hatching_data"],
        "nest_success_sp_beach_drawn": ["nesting_success_species_beach_df"],
        "persist_nest_success_sp_beach": ["nest_success_sp_beach_drawn"],
        "nest_success_sp_beach_widget": ["persist_nest_success_sp_beach"],
        "nesting_success_manipulation_df": ["hatching_data"],
        "nest_success_manip_drawn": ["nesting_success_manipulation_df"],
        "persist_nest_success_manip": ["nest_success_manip_drawn"],
        "nest_success_manip_widget": ["persist_nest_success_manip"],
        "turtle_colormap": ["turtle_data"],
        "turtle_layer": ["turtle_colormap"],
        "turtle_map": ["turtle_layer", "base_maps"],
        "persist_turtle_map": ["turtle_map"],
        "turtle_map_widget": ["persist_turtle_map"],
        "turtle_events_by_location_df": ["turtle_data"],
        "turtle_events_by_location_drawn": ["turtle_events_by_location_df"],
        "persist_turtle_events_by_loc": ["turtle_events_by_location_drawn"],
        "turtle_events_by_location_widget": ["persist_turtle_events_by_loc"],
        "fp_by_location_df": ["turtle_data"],
        "fp_by_location_drawn": ["fp_by_location_df"],
        "persist_fp_by_location": ["fp_by_location_drawn"],
        "fp_by_location_widget": ["persist_fp_by_location"],
        "dashboard": [
            "workflow_details",
            "total_nesting_widget",
            "total_hatched_eggs_widget",
            "hatching_success_widget",
            "total_turtle_widget",
            "total_fp_widget",
            "nesting_map_widget",
            "nesting_over_time_widget",
            "nesting_by_beach_widget",
            "nest_success_sp_beach_widget",
            "nest_success_manip_widget",
            "turtle_map_widget",
            "turtle_events_by_location_widget",
            "fp_by_location_widget",
            "time_range",
        ],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "er_client": Node(
            async_task=set_er_connection.validate()
            .set_task_instance_id("er_client")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("er_client") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_format": "%d %b %Y",
            }
            | (params_dict.get("time_range") or {}),
            method="call",
        ),
        "base_maps": Node(
            async_task=set_base_maps_pydeck.validate()
            .set_task_instance_id("base_maps")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("base_maps") or {}),
            method="call",
        ),
        "all_events": Node(
            async_task=get_events.validate()
            .set_task_instance_id("all_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client"),
                "time_range": DependsOn("time_range"),
                "event_columns": [
                    "id",
                    "time",
                    "event_type",
                    "geometry",
                    "event_details",
                ],
                "event_types": [
                    "suspected_nest_v2",
                    "attempt_v2",
                    "dry_run_v2",
                    "hatching_data",
                    "relocation_data_v2",
                    "turtle_data_form_v2",
                ],
                "include_details": True,
                "include_display_values": True,
                "raise_on_empty": False,
                "include_updates": False,
                "include_related_events": False,
                "include_null_geometry": False,
            }
            | (params_dict.get("all_events") or {}),
            method="call",
        ),
        "all_events_processed": Node(
            async_task=process_events_details.validate()
            .set_task_instance_id("all_events_processed")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("all_events"),
                "client": DependsOn("er_client"),
                "map_to_titles": False,
                "ordered": False,
            }
            | (params_dict.get("all_events_processed") or {}),
            method="call",
        ),
        "nesting_events_raw": Node(
            async_task=filter_row_values.validate()
            .set_task_instance_id("nesting_events_raw")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("all_events_processed"),
                "column": "event_type",
                "values": [
                    "suspected_nest_v2",
                    "attempt_v2",
                    "dry_run_v2",
                ],
            }
            | (params_dict.get("nesting_events_raw") or {}),
            method="call",
        ),
        "map_nesting_events_raw": Node(
            async_task=filter_row_values.validate()
            .set_task_instance_id("map_nesting_events_raw")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("all_events_processed"),
                "column": "event_type",
                "values": [
                    "suspected_nest_v2",
                    "attempt_v2",
                    "relocation_data_v2",
                ],
            }
            | (params_dict.get("map_nesting_events_raw") or {}),
            method="call",
        ),
        "suspected_nest_events": Node(
            async_task=filter_row_values.validate()
            .set_task_instance_id("suspected_nest_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("all_events_processed"),
                "column": "event_type",
                "values": [
                    "suspected_nest_v2",
                ],
            }
            | (params_dict.get("suspected_nest_events") or {}),
            method="call",
        ),
        "hatching_events": Node(
            async_task=filter_row_values.validate()
            .set_task_instance_id("hatching_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("all_events_processed"),
                "column": "event_type",
                "values": [
                    "hatching_data",
                ],
            }
            | (params_dict.get("hatching_events") or {}),
            method="call",
        ),
        "turtle_events": Node(
            async_task=filter_row_values.validate()
            .set_task_instance_id("turtle_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("all_events_processed"),
                "column": "event_type",
                "values": [
                    "turtle_data_form_v2",
                ],
            }
            | (params_dict.get("turtle_events") or {}),
            method="call",
        ),
        "nesting_data": Node(
            async_task=extract_nesting_fields.validate()
            .set_task_instance_id("nesting_data")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("nesting_events_raw"),
            }
            | (params_dict.get("nesting_data") or {}),
            method="call",
        ),
        "map_nesting_data": Node(
            async_task=extract_nesting_fields.validate()
            .set_task_instance_id("map_nesting_data")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("map_nesting_events_raw"),
            }
            | (params_dict.get("map_nesting_data") or {}),
            method="call",
        ),
        "suspected_nest_data": Node(
            async_task=extract_nesting_fields.validate()
            .set_task_instance_id("suspected_nest_data")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("suspected_nest_events"),
            }
            | (params_dict.get("suspected_nest_data") or {}),
            method="call",
        ),
        "hatching_data": Node(
            async_task=extract_hatching_fields.validate()
            .set_task_instance_id("hatching_data")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("hatching_events"),
            }
            | (params_dict.get("hatching_data") or {}),
            method="call",
        ),
        "turtle_data": Node(
            async_task=extract_turtle_fields.validate()
            .set_task_instance_id("turtle_data")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("turtle_events"),
            }
            | (params_dict.get("turtle_data") or {}),
            method="call",
        ),
        "total_nesting_count": Node(
            async_task=dataframe_count.validate()
            .set_task_instance_id("total_nesting_count")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("nesting_events_raw"),
            }
            | (params_dict.get("total_nesting_count") or {}),
            method="call",
        ),
        "total_nesting_widget": Node(
            async_task=create_single_value_widget_single_view.validate()
            .set_task_instance_id("total_nesting_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Total Nesting Events",
                "decimal_places": 0,
                "data": DependsOn("total_nesting_count"),
            }
            | (params_dict.get("total_nesting_widget") or {}),
            method="call",
        ),
        "total_hatched_eggs": Node(
            async_task=dataframe_column_sum.validate()
            .set_task_instance_id("total_hatched_eggs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("hatching_data"),
                "column_name": "hatchedempty_egg_shells",
            }
            | (params_dict.get("total_hatched_eggs") or {}),
            method="call",
        ),
        "total_hatched_eggs_widget": Node(
            async_task=create_single_value_widget_single_view.validate()
            .set_task_instance_id("total_hatched_eggs_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Total Hatched Eggs",
                "decimal_places": 0,
                "data": DependsOn("total_hatched_eggs"),
            }
            | (params_dict.get("total_hatched_eggs_widget") or {}),
            method="call",
        ),
        "hatching_success_pct": Node(
            async_task=compute_hatching_success_pct.validate()
            .set_task_instance_id("hatching_success_pct")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("hatching_data"),
            }
            | (params_dict.get("hatching_success_pct") or {}),
            method="call",
        ),
        "hatching_success_widget": Node(
            async_task=create_single_value_widget_single_view.validate()
            .set_task_instance_id("hatching_success_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Hatching Success (%)",
                "decimal_places": 1,
                "data": DependsOn("hatching_success_pct"),
            }
            | (params_dict.get("hatching_success_widget") or {}),
            method="call",
        ),
        "total_turtle_count": Node(
            async_task=dataframe_count.validate()
            .set_task_instance_id("total_turtle_count")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("turtle_events"),
            }
            | (params_dict.get("total_turtle_count") or {}),
            method="call",
        ),
        "total_turtle_widget": Node(
            async_task=create_single_value_widget_single_view.validate()
            .set_task_instance_id("total_turtle_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Total Turtle-Related Events",
                "decimal_places": 0,
                "data": DependsOn("total_turtle_count"),
            }
            | (params_dict.get("total_turtle_widget") or {}),
            method="call",
        ),
        "fp_events": Node(
            async_task=filter_df.validate()
            .set_task_instance_id("fp_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("turtle_data"),
                "column_name": "fibropapillomatosis",
                "op": "equal",
                "value": "yes",
                "reset_index": True,
            }
            | (params_dict.get("fp_events") or {}),
            method="call",
        ),
        "total_fp_count": Node(
            async_task=dataframe_count.validate()
            .set_task_instance_id("total_fp_count")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("fp_events"),
            }
            | (params_dict.get("total_fp_count") or {}),
            method="call",
        ),
        "total_fp_widget": Node(
            async_task=create_single_value_widget_single_view.validate()
            .set_task_instance_id("total_fp_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Total Turtles with FP",
                "decimal_places": 0,
                "data": DependsOn("total_fp_count"),
            }
            | (params_dict.get("total_fp_widget") or {}),
            method="call",
        ),
        "nesting_colormap": Node(
            async_task=apply_qualitative_color_map.validate()
            .set_task_instance_id("nesting_colormap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("map_nesting_data"),
                "input_column_name": "event_type_display",
                "colormap": "Set1",
            }
            | (params_dict.get("nesting_colormap") or {}),
            method="call",
        ),
        "nesting_layer": Node(
            async_task=create_scatterplot_layer.validate()
            .set_task_instance_id("nesting_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geodataframe": DependsOn("nesting_colormap"),
                "layer_style": {
                    "get_fill_color": "column_color",
                    "get_radius": 5,
                    "radius_units": "pixels",
                },
                "legend": {
                    "title": "Nesting Activity",
                    "label_column": "column_label",
                    "color_column": "column_color",
                },
                "data_url": None,
            }
            | (params_dict.get("nesting_layer") or {}),
            method="call",
        ),
        "nesting_map": Node(
            async_task=draw_map.validate()
            .set_task_instance_id("nesting_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geo_layers": DependsOn("nesting_layer"),
                "tile_layers": DependsOn("base_maps"),
                "static": False,
                "title": None,
                "max_zoom": 15,
                "view_state": None,
                "legend_style": {
                    "placement": "bottom-right",
                },
            }
            | (params_dict.get("nesting_map") or {}),
            method="call",
        ),
        "persist_nesting_map": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_nesting_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("nesting_map"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "nesting_map",
            }
            | (params_dict.get("persist_nesting_map") or {}),
            method="call",
        ),
        "nesting_map_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("nesting_map_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Nesting Activity Map",
                "data": DependsOn("persist_nesting_map"),
            }
            | (params_dict.get("nesting_map_widget") or {}),
            method="call",
        ),
        "nesting_over_time_agg": Node(
            async_task=aggregate_nesting_by_month_species.validate()
            .set_task_instance_id("nesting_over_time_agg")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("nesting_data"),
            }
            | (params_dict.get("nesting_over_time_agg") or {}),
            method="call",
        ),
        "nesting_over_time_chart": Node(
            async_task=draw_line_chart.validate()
            .set_task_instance_id("nesting_over_time_chart")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("nesting_over_time_agg"),
                "x_column": "time",
                "y_column": "count",
                "category_column": "specie",
                "layout_kwargs": {
                    "xaxis": {
                        "title": "Month",
                    },
                    "yaxis": {
                        "title": "Nesting Events",
                    },
                },
                "widget_id": "nesting_over_time_widget",
            }
            | (params_dict.get("nesting_over_time_chart") or {}),
            method="call",
        ),
        "persist_nesting_over_time": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_nesting_over_time")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("nesting_over_time_chart"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "nesting_over_time",
            }
            | (params_dict.get("persist_nesting_over_time") or {}),
            method="call",
        ),
        "nesting_over_time_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("nesting_over_time_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Nesting Activity Over Time",
                "data": DependsOn("persist_nesting_over_time"),
            }
            | (params_dict.get("nesting_over_time_widget") or {}),
            method="call",
        ),
        "nesting_by_beach_df": Node(
            async_task=create_nesting_by_beach_table.validate()
            .set_task_instance_id("nesting_by_beach_df")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("nesting_data"),
            }
            | (params_dict.get("nesting_by_beach_df") or {}),
            method="call",
        ),
        "nesting_by_beach_drawn": Node(
            async_task=draw_table.validate()
            .set_task_instance_id("nesting_by_beach_drawn")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("nesting_by_beach_df"),
                "columns": None,
                "table_config": None,
                "widget_id": "nesting_by_beach_widget",
            }
            | (params_dict.get("nesting_by_beach_drawn") or {}),
            method="call",
        ),
        "persist_nesting_by_beach": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_nesting_by_beach")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("nesting_by_beach_drawn"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "nesting_by_beach",
            }
            | (params_dict.get("persist_nesting_by_beach") or {}),
            method="call",
        ),
        "nesting_by_beach_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("nesting_by_beach_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Total Nesting Activity by Beach",
                "data": DependsOn("persist_nesting_by_beach"),
            }
            | (params_dict.get("nesting_by_beach_widget") or {}),
            method="call",
        ),
        "nesting_success_species_beach_df": Node(
            async_task=create_nesting_success_by_species_beach_table.validate()
            .set_task_instance_id("nesting_success_species_beach_df")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("hatching_data"),
            }
            | (params_dict.get("nesting_success_species_beach_df") or {}),
            method="call",
        ),
        "nest_success_sp_beach_drawn": Node(
            async_task=draw_table.validate()
            .set_task_instance_id("nest_success_sp_beach_drawn")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("nesting_success_species_beach_df"),
                "columns": None,
                "table_config": None,
                "widget_id": "nest_success_sp_beach_widget",
            }
            | (params_dict.get("nest_success_sp_beach_drawn") or {}),
            method="call",
        ),
        "persist_nest_success_sp_beach": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_nest_success_sp_beach")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("nest_success_sp_beach_drawn"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "nesting_success_species_beach",
            }
            | (params_dict.get("persist_nest_success_sp_beach") or {}),
            method="call",
        ),
        "nest_success_sp_beach_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("nest_success_sp_beach_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Nesting Success by Species & Beach",
                "data": DependsOn("persist_nest_success_sp_beach"),
            }
            | (params_dict.get("nest_success_sp_beach_widget") or {}),
            method="call",
        ),
        "nesting_success_manipulation_df": Node(
            async_task=create_nesting_success_by_manipulation_table.validate()
            .set_task_instance_id("nesting_success_manipulation_df")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("hatching_data"),
            }
            | (params_dict.get("nesting_success_manipulation_df") or {}),
            method="call",
        ),
        "nest_success_manip_drawn": Node(
            async_task=draw_table.validate()
            .set_task_instance_id("nest_success_manip_drawn")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("nesting_success_manipulation_df"),
                "columns": None,
                "table_config": None,
                "widget_id": "nest_success_manip_widget",
            }
            | (params_dict.get("nest_success_manip_drawn") or {}),
            method="call",
        ),
        "persist_nest_success_manip": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_nest_success_manip")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("nest_success_manip_drawn"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "nesting_success_manipulation",
            }
            | (params_dict.get("persist_nest_success_manip") or {}),
            method="call",
        ),
        "nest_success_manip_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("nest_success_manip_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Nesting Success by Nest Manipulation",
                "data": DependsOn("persist_nest_success_manip"),
            }
            | (params_dict.get("nest_success_manip_widget") or {}),
            method="call",
        ),
        "turtle_colormap": Node(
            async_task=apply_qualitative_color_map.validate()
            .set_task_instance_id("turtle_colormap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("turtle_data"),
                "input_column_name": "activity_type",
                "colormap": "Set2",
            }
            | (params_dict.get("turtle_colormap") or {}),
            method="call",
        ),
        "turtle_layer": Node(
            async_task=create_scatterplot_layer.validate()
            .set_task_instance_id("turtle_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geodataframe": DependsOn("turtle_colormap"),
                "layer_style": {
                    "get_fill_color": "column_color",
                    "get_radius": 5,
                    "radius_units": "pixels",
                },
                "legend": {
                    "title": "Turtle Events",
                    "label_column": "column_label",
                    "color_column": "column_color",
                },
                "data_url": None,
            }
            | (params_dict.get("turtle_layer") or {}),
            method="call",
        ),
        "turtle_map": Node(
            async_task=draw_map.validate()
            .set_task_instance_id("turtle_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geo_layers": DependsOn("turtle_layer"),
                "tile_layers": DependsOn("base_maps"),
                "static": False,
                "title": None,
                "max_zoom": 15,
                "view_state": None,
                "legend_style": {
                    "placement": "bottom-right",
                },
            }
            | (params_dict.get("turtle_map") or {}),
            method="call",
        ),
        "persist_turtle_map": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_turtle_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("turtle_map"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "turtle_map",
            }
            | (params_dict.get("persist_turtle_map") or {}),
            method="call",
        ),
        "turtle_map_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("turtle_map_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Turtle-Related Events Map",
                "data": DependsOn("persist_turtle_map"),
            }
            | (params_dict.get("turtle_map_widget") or {}),
            method="call",
        ),
        "turtle_events_by_location_df": Node(
            async_task=create_turtle_events_by_location_table.validate()
            .set_task_instance_id("turtle_events_by_location_df")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("turtle_data"),
            }
            | (params_dict.get("turtle_events_by_location_df") or {}),
            method="call",
        ),
        "turtle_events_by_location_drawn": Node(
            async_task=draw_table.validate()
            .set_task_instance_id("turtle_events_by_location_drawn")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("turtle_events_by_location_df"),
                "columns": None,
                "table_config": None,
                "widget_id": "turtle_events_by_location_widget",
            }
            | (params_dict.get("turtle_events_by_location_drawn") or {}),
            method="call",
        ),
        "persist_turtle_events_by_loc": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_turtle_events_by_loc")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("turtle_events_by_location_drawn"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "turtle_events_by_location",
            }
            | (params_dict.get("persist_turtle_events_by_loc") or {}),
            method="call",
        ),
        "turtle_events_by_location_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("turtle_events_by_location_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Turtle Events by Location & Activity",
                "data": DependsOn("persist_turtle_events_by_loc"),
            }
            | (params_dict.get("turtle_events_by_location_widget") or {}),
            method="call",
        ),
        "fp_by_location_df": Node(
            async_task=create_fp_by_location_table.validate()
            .set_task_instance_id("fp_by_location_df")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("turtle_data"),
            }
            | (params_dict.get("fp_by_location_df") or {}),
            method="call",
        ),
        "fp_by_location_drawn": Node(
            async_task=draw_table.validate()
            .set_task_instance_id("fp_by_location_drawn")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("fp_by_location_df"),
                "columns": None,
                "table_config": None,
                "widget_id": "fp_by_location_widget",
            }
            | (params_dict.get("fp_by_location_drawn") or {}),
            method="call",
        ),
        "persist_fp_by_location": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_fp_by_location")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("fp_by_location_drawn"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "fp_by_location",
            }
            | (params_dict.get("persist_fp_by_location") or {}),
            method="call",
        ),
        "fp_by_location_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("fp_by_location_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "FP Monitoring by Location",
                "data": DependsOn("persist_fp_by_location"),
            }
            | (params_dict.get("fp_by_location_widget") or {}),
            method="call",
        ),
        "dashboard": Node(
            async_task=gather_curacao_dashboard.validate()
            .set_task_instance_id("dashboard")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "widgets": [
                    DependsOn("total_nesting_widget"),
                    DependsOn("total_hatched_eggs_widget"),
                    DependsOn("hatching_success_widget"),
                    DependsOn("total_turtle_widget"),
                    DependsOn("total_fp_widget"),
                    DependsOn("nesting_map_widget"),
                    DependsOn("nesting_over_time_widget"),
                    DependsOn("nesting_by_beach_widget"),
                    DependsOn("nest_success_sp_beach_widget"),
                    DependsOn("nest_success_manip_widget"),
                    DependsOn("turtle_map_widget"),
                    DependsOn("turtle_events_by_location_widget"),
                    DependsOn("fp_by_location_widget"),
                ],
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
