workflow_details:
  name: "Curacao Turtle Monitoring"
  description: ""
er_client:
  data_source:
    name: curacao
time_range:
  since: "2025-01-01T00:00:00.000Z"
  until: "2026-07-01T00:00:00.000Z"
nesting_colormap: {}
turtle_colormap: {}
